@startuml

class User extends UriEntity implements UserDetails {
    username : String
    password : String
    email : String
}

class UriEntity {
    uri : String
}

class Admin extends User {}
class Student extends User {}
class Owner extends User {}

class Property extends UriEntity {
    description : String
}

class Apartment extends Property {
    street : String
    number : String
    city : String
}
Owner "1" --up-- "*" Apartment : owner <

class Room extends Property {
}
Apartment "1" --left-- "*" Room : in <

class Advertisement extends UriEntity {
    title : String
    description : String
    price : Double
}
Property "1" --right-- "*" Advertisement : about <

class Visit extends UriEntity {
    when : ZonedDateTime
}
Advertisement "1" --right-- "*" Visit : for <
Student "1" --left-- "*" Visit : visitor <

@enduml
