app = 'myapartments-api'
primary_region = 'mad'
swap_size_mb = 512

[build]

[env]
  JAVA_OPTS = '-XX:MaxRAM=70m'
  SERVER_FORWARD_HEADERS_STRATEGY = 'NATIVE'
  SPRING_PROFILES_ACTIVE = 'flyio'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
  port = 80
  handlers = ['http']
  force_https = true

[[services.ports]]
  port = 443
  handlers = ['tls', 'http']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
